services:
  # frontend:
  #   image: ghcr.io/nctucsunion/cs15night:frontend
  #   container_name: 15night_frontend
  #   restart: always
  #   ports:
  #     - "8081:4173"
  frontend-admin:
    image: ghcr.io/nctucsunion/cs15night:frontend-admin
    container_name: 15night_frontend_admin
    restart: always
    ports:
      - "8082:4173"
  backend:
    image: ghcr.io/nctucsunion/cs15night:backend
    container_name: 15night_backend
    restart: always
    ports:
      - "8321:8000"
    env_file:
      - ./backend/.env.prod

volumes:
  mysql_data: